void head(char mas[]);
void yellow();
void white();
void red();
void green();
double f(double x, double y);
double f(double x1, double y1, double x2, double y2);
int f(int a);
int f(int a, int b);
int f(int a, int b, int c);
void swap(int* a, int* b);
void swap(int& a, int& b);